### ISSUE TITLE
Improvements to the tool

### ISSUE THREAD

**Issue by Nipeno** [RatScanner/RatScanner#15]
Been loving the tool, but I had some ideas for improvements.
- Show if item is needed for quest (highlight in a color or so)
- Show if item is needed for upgrading the hideout
- With minimal UI enabled only show the UI once scanning a item and make it disappear after like 5 seconds

Amazing work, thanks for sharing this publicly.
I'll donate some money if you actually add any of these features lol

**Comment by Blightbuster** [comment]
> With minimal UI enabled only show the UI once scanning a item and make it disappear after like 5 seconds

Tracked by [this card](https://github.com/Blightbuster/RatScanner/projects/1#card-46675784)

>Show if item is needed for quest (highlight in a color or so)
>Show if item is needed for upgrading the hideout

Tracked by [this card](https://github.com/Blightbuster/RatScanner/projects/2#card-46665236)

> I'll donate some money if you actually add any of these features lol

Easiest cash grab in my life 😄 

_Sorry for the project board mess 🙃_

**Comment by gcatellani** [comment]
Hi. **I would like to use another (modifier) key then CTRL, ALT or SHIFT for "Icon scan modifier"** as I already use these three modifier keys in Tarkov. Ctrl+LMB for transfers between containers, Alt+LMB to put equipment on by char, and Shift+LMB to drop/destroy items; this way I'm super fast when looting as I just need to switch the modifier key for the different actions.

Thank you for the development of RatScanner. It's awesome. But to be honest I still will refrain on using it until a BSG dev says whether it could get us a ban or not.

P.S.: I'm not sure whether https://github.com/Blightbuster/RatScanner/projects/2#card-46671849 already covers my improvement wish and I'm also unsure whether or not you would like a new "Issue" to be opened or for any improvement wishes to go into this "Issue", but I just went ahead anyway ;-)

**Comment by Blightbuster** [comment]
> Thank you for the development of RatScanner. It's awesome. But to be honest I still will refrain on using it until a BSG dev says whether it could get us a ban or not (and yes I know how RatScanner works but still BSG/BattleEye could take offence in the tool as they could argue that it breaks immersion or some such thing and detect it running and ban somebody for using it).

Yeah. Its a dragging process... Not sure if / when anyone from bsg will respond to my messages.

As you already mentioned its a planned feature. Currently there are some other priorities for this project though like having it in a functional state for everyone to use.

If you want, you can already change the key to any you like by editing the config file. Just change the entry to the key code of your liking.

Here is a list of keycodes:
https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.keys?view=netcore-3.1

> P.S.: I'm not sure whether https://github.com/Blightbuster/RatScanner/projects/2#card-46671849 already covers my improvement wish and I'm also unsure whether or not you would like a new "Issue" to be opened or for any improvement wishes to go into this "Issue", but I just went ahead anyway ;-)

I would appreciate it having one issue for every request / bug since it makes it much easier to track them. For that matter please open a new issue with this feature request if you want to discuss / give some more input on it.

**Comment by gcatellani** [comment]
Thank you very much. As per your request I created a new "Enhancement"-ticket [here](https://github.com/Blightbuster/RatScanner/issues/37).

**Comment by Elmegaard** [comment]
I wanted to help you so I wrote a small python script that scans through the wiki and searches for hideout and quest items and exports them to a json format. You can just re-run the tool to get the latest data if the wiki is updated. I noticed a few quests that didn't have the "found in raid" text even though I know the quest requires that after the latest patch, but I guess it will be updated at some point.

It will export some items which are not items, but for example "Jaeger" shows up as an item, but I don't think it will be an issue as long as you just do a lookup in the json. You can just ship the output along with the tool or something like that.
https://github.com/Elmegaard/TarkovWikiScanner

**Comment by namrog84** [comment]
@Nipeno per your original issue 

* Show if item is needed for quest (highlight in a color or so)
* Show if item is needed for upgrading the hideout

The most recent version has added 2 new icons on the window to display it. It integrates with tarkov-tracker so that it is specific to your needs of what you (or tt teammate) specifically need.
