### ISSUE TITLE
Name Scan language reset to Chinese after update

### ISSUE THREAD

**Issue by brikr** [RatScanner/RatScanner#302]
**Describe the bug**
My "Name Scan Language" setting was set to Chinese after updating from 3.1.0 to 3.2.1. It was set to English before

**To Reproduce**
I haven't tried to manually reproduce again, but here's what I did:
- Have 3.1.0 installed _without_ RatUpdater.exe (not sure why I didn't have it)
- Download 3.2.1 from GH releases
- Extract and drag 3.2.1 into same directory as 3.1.0, ask Windows to replace files
- Boot up 3.2.1, language is Chinese

**Comment by brikr** [comment]
Realizing now that language support was _added_ in 3.2.1. Is there a way y'all could detect system language or ask the user the first time instead of choosing the first language in the list?

**Comment by Blightbuster** [comment]
The default language is english not chinese. The issue your experiencing is because your old config has the language already set to `0` which previously referred to english but now referrs to chinese (since thats the order BSG chose for them).

I decided to take this "harsh cut" to adhere to the games internal data structure with the knowledge in the back of my head that, due to the mistake of me not including the updater in the previous version, people had to update (and with that I assumed discard their config) anyways.

Im not sure about detecting the system language either since I personally and the majority of players I know, play in english regardless of their system language.
