### ISSUE TITLE
Issues with rotation, insurance and worn items

### ISSUE THREAD

**Issue by EredLithui** [RatScanner/RatScanner#31]
Hey there, thanks a lot for sharing your tool with us. I haven't had much time to try it out but stumbled upon a few hiccups that seem to be connected to rotation, surrounding and worn items.

A few examples (clicking items has no effect or shows wrong items):
6L31 depends on rotation and shows TT pistol (or when overlay text pops up toilet paper, Standard 9x18PM 20mag/MPX 20mag, cowboy hat and more though that's a rather special case)
6B3TM-01M depends on rotation, shows no/different items (in inventory)
SSh-68 worn shows no/wrong items depending on the location, in inventory it works
AKS-74U shows THICC weapon case when worn, works in inventory
GSSh-01 not working when worn, works in inventory
CMS seems to be dependent on usage (5/5 works, 2/5 rotated doesn't)

A few of the rotation bugs can be avoided by placing the items next to other items (6B3 for example).

Additional:
Not a single item in my rig works but in the stash/inventory they do.
Keys/cards don't work at all

I'm using a QHD monitor for EFT and my second monitor is FHD. Windows scaling is set to 100%.

![eft_ratscanner](https://user-images.githubusercontent.com/8452742/95321404-4d9cb200-089b-11eb-9f19-9a7588382d16.png)

**Comment by Blightbuster** [comment]
For some of them, you are trying to scan them when they are in the equiped slots. This is currently not supported since those result in different scaling of the items.

For the others: are you perhaps trying to scan items which are high up in the stash? There is currently a issue with that more detail here: https://github.com/Blightbuster/RatScanner/blob/master/FAQ.md#icon-scanning-gets-a-lot-of-wrong-matches

Also on the image in the top left corner I spot that there is the tarkov tooltip showing which hides the item below hence makes it hard for the item to be detected correctly.

**Comment by Blightbuster** [comment]
Please comment if this issue persists in the latest version and I will reopen this issue.
