### ISSUE TITLE
Overlay icons too small at 1440p

### ISSUE THREAD

**Issue by Nanorithm** [RatScanner/RatScanner#343]
**Describe the bug**
When using the in game shift + click search, the icon is too small. Resolution is 1440p, 165Hz monitor, borderless, Windows 10.

**To Reproduce**
1. Shift + Click on Item at 1440p resolution

**Expected behavior**
Icon should be the proper size

**Screenshots**
![image](https://user-images.githubusercontent.com/13856563/153691908-86957e06-e19b-47c7-a0a3-87f1e9b35528.png)

**Comment by aVitomin** [comment]
Any news about fix ?

**Comment by Blightbuster** [comment]
Hey, so I've been trying to fix this ok the past few days however at the moment I'm unable to find a reliable. The issue being that since in windows multi monitor setups which already have different dpi values can also have different scaling and the current framework I'm using doesn't expose raw pixel data which is needed but only virtualized pixels (which get adjusted in size depending on dpi / scale.

**Comment by Blightbuster** [comment]
I got two more ideas which I will try tomorrow but if they don't work out, I will postpone the fix to the next update.

**Comment by Blightbuster** [comment]
Thanks for submitting the issue, to keep things organized it will from now on be tracked in #173.
