### ISSUE TITLE
Flea Market Prices are completely wrong

### ISSUE THREAD

**Issue by gadzzy** [RatScanner/RatScanner#444]
**Describe the bug**
Scanning works correctly, Prices are completely inaccurate. 

**To Reproduce**
1. Launch Rat Scanner
2. Scan Any Item

**Expected behavior**
The prices to be accurate to the Flea Market.

**Screenshots**
![image](https://user-images.githubusercontent.com/121647363/210023712-ac61d1ce-a046-4c0d-9959-0e3a4c49fc59.png)
![image](https://user-images.githubusercontent.com/121647363/210023722-f8327a3e-c9ea-44de-b366-8e2d0cae0731.png)

**Comment by Blightbuster** [comment]
Hey, prices are sourced from https://tarkov.dev/ since the game was just wiped recently, it needs some time until accounts are leveled to be able to access the flea market. The first account is actually already level 15 and just now starting to collect prices so we should see up to date prices in at most ~2h. Prices will get more frequent updates as more scanner accounts are leveled up.
